System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "euler/euler-bundle.js": [
      "euler/index.js",
      "npm:babel-runtime@5.8.35/core-js/promise",
      "github:mbostock/d3@3.5.14",
      "euler/euler.js",
      "npm:core-js@1.2.6/library/fn/promise",
      "npm:core-js@1.2.6/library/modules/es6.object.to-string",
      "npm:core-js@1.2.6/library/modules/es6.string.iterator",
      "euler/euler.html!github:systemjs/plugin-text@0.0.4",
      "npm:mathjs@2.6.0",
      "npm:core-js@1.2.6/library/modules/web.dom.iterable",
      "npm:core-js@1.2.6/library/modules/es6.promise",
      "npm:core-js@1.2.6/library/modules/$.core",
      "github:mbostock/d3@3.5.14/d3",
      "npm:core-js@1.2.6/library/modules/$.iterators",
      "npm:core-js@1.2.6/library/modules/$",
      "npm:core-js@1.2.6/library/modules/$.global",
      "npm:core-js@1.2.6/library/modules/$.library",
      "npm:core-js@1.2.6/library/modules/$.string-at",
      "npm:core-js@1.2.6/library/modules/es6.array.iterator",
      "npm:core-js@1.2.6/library/modules/$.iter-define",
      "npm:mathjs@2.6.0/index",
      "npm:core-js@1.2.6/library/modules/$.ctx",
      "npm:core-js@1.2.6/library/modules/$.classof",
      "npm:core-js@1.2.6/library/modules/$.is-object",
      "npm:core-js@1.2.6/library/modules/$.strict-new",
      "npm:core-js@1.2.6/library/modules/$.a-function",
      "npm:core-js@1.2.6/library/modules/$.same-value",
      "npm:core-js@1.2.6/library/modules/$.export",
      "npm:core-js@1.2.6/library/modules/$.for-of",
      "npm:core-js@1.2.6/library/modules/$.set-proto",
      "npm:core-js@1.2.6/library/modules/$.species-constructor",
      "npm:core-js@1.2.6/library/modules/$.wks",
      "npm:core-js@1.2.6/library/modules/$.redefine-all",
      "npm:core-js@1.2.6/library/modules/$.descriptors",
      "npm:core-js@1.2.6/library/modules/$.set-to-string-tag",
      "npm:core-js@1.2.6/library/modules/$.an-object",
      "npm:core-js@1.2.6/library/modules/$.microtask",
      "npm:core-js@1.2.6/library/modules/$.set-species",
      "github:jspm/nodelibs-process@0.1.2",
      "npm:core-js@1.2.6/library/modules/$.iter-detect",
      "npm:core-js@1.2.6/library/modules/$.to-integer",
      "npm:core-js@1.2.6/library/modules/$.defined",
      "npm:core-js@1.2.6/library/modules/$.add-to-unscopables",
      "npm:core-js@1.2.6/library/modules/$.iter-step",
      "npm:core-js@1.2.6/library/modules/$.has",
      "npm:core-js@1.2.6/library/modules/$.to-iobject",
      "npm:core-js@1.2.6/library/modules/$.redefine",
      "npm:core-js@1.2.6/library/modules/$.hide",
      "npm:core-js@1.2.6/library/modules/$.iter-create",
      "npm:mathjs@2.6.0/core",
      "npm:core-js@1.2.6/library/modules/$.cof",
      "npm:core-js@1.2.6/library/modules/$.uid",
      "npm:core-js@1.2.6/library/modules/$.fails",
      "npm:mathjs@2.6.0/lib/index",
      "npm:core-js@1.2.6/library/modules/$.is-array-iter",
      "npm:core-js@1.2.6/library/modules/$.to-length",
      "npm:core-js@1.2.6/library/modules/$.iter-call",
      "npm:core-js@1.2.6/library/modules/core.get-iterator-method",
      "npm:core-js@1.2.6/library/modules/$.shared",
      "npm:core-js@1.2.6/library/modules/$.task",
      "github:jspm/nodelibs-process@0.1.2/index",
      "npm:core-js@1.2.6/library/modules/$.property-desc",
      "npm:core-js@1.2.6/library/modules/$.invoke",
      "npm:core-js@1.2.6/library/modules/$.iobject",
      "npm:mathjs@2.6.0/lib/core/core",
      "npm:mathjs@2.6.0/lib/type/index",
      "npm:mathjs@2.6.0/lib/constants",
      "npm:mathjs@2.6.0/lib/json/index",
      "npm:mathjs@2.6.0/lib/expression/index",
      "npm:mathjs@2.6.0/lib/error/index",
      "npm:core-js@1.2.6/library/modules/$.html",
      "npm:core-js@1.2.6/library/modules/$.dom-create",
      "npm:mathjs@2.6.0/lib/function/index",
      "npm:process@0.11.2",
      "npm:mathjs@2.6.0/lib/utils/emitter",
      "npm:mathjs@2.6.0/lib/utils/object",
      "npm:mathjs@2.6.0/lib/version",
      "npm:mathjs@2.6.0/lib/json/reviver",
      "npm:mathjs@2.6.0/lib/core/config",
      "npm:mathjs@2.6.0/lib/core/import",
      "npm:mathjs@2.6.0/lib/type/bignumber/index",
      "npm:mathjs@2.6.0/lib/type/boolean",
      "npm:mathjs@2.6.0/lib/type/complex/index",
      "npm:mathjs@2.6.0/lib/type/fraction/index",
      "npm:mathjs@2.6.0/lib/type/number",
      "npm:mathjs@2.6.0/lib/type/resultset/index",
      "npm:mathjs@2.6.0/lib/type/chain/index",
      "npm:mathjs@2.6.0/lib/type/matrix/index",
      "npm:mathjs@2.6.0/lib/type/unit/index",
      "npm:mathjs@2.6.0/lib/utils/array",
      "npm:mathjs@2.6.0/lib/utils/bignumber/constants",
      "npm:mathjs@2.6.0/lib/expression/docs/index",
      "npm:mathjs@2.6.0/lib/expression/function/index",
      "npm:mathjs@2.6.0/lib/expression/node/index",
      "npm:mathjs@2.6.0/lib/expression/transform/index",
      "npm:mathjs@2.6.0/lib/expression/Help",
      "npm:mathjs@2.6.0/lib/core/typed",
      "npm:mathjs@2.6.0/lib/type/string",
      "npm:mathjs@2.6.0/lib/error/DimensionError",
      "npm:mathjs@2.6.0/lib/error/IndexError",
      "npm:mathjs@2.6.0/lib/expression/Parser",
      "npm:mathjs@2.6.0/lib/expression/parse",
      "npm:mathjs@2.6.0/lib/error/ArgumentsError",
      "npm:mathjs@2.6.0/lib/function/algebra/index",
      "npm:mathjs@2.6.0/lib/function/bitwise/index",
      "npm:mathjs@2.6.0/lib/function/combinatorics/index",
      "npm:mathjs@2.6.0/lib/function/complex/index",
      "npm:mathjs@2.6.0/lib/function/geometry/index",
      "npm:mathjs@2.6.0/lib/function/matrix/index",
      "npm:mathjs@2.6.0/lib/function/probability/index",
      "npm:mathjs@2.6.0/lib/function/statistics/index",
      "npm:mathjs@2.6.0/lib/function/logical/index",
      "npm:mathjs@2.6.0/lib/function/relational/index",
      "npm:process@0.11.2/browser",
      "npm:mathjs@2.6.0/lib/function/trigonometry/index",
      "npm:mathjs@2.6.0/lib/function/arithmetic/index",
      "npm:mathjs@2.6.0/lib/function/utils/index",
      "npm:mathjs@2.6.0/lib/function/units/index",
      "npm:tiny-emitter@1.0.2",
      "npm:mathjs@2.6.0/lib/utils/collection/deepMap",
      "npm:mathjs@2.6.0/lib/type/chain/function/chain",
      "npm:mathjs@2.6.0/lib/type/resultset/ResultSet",
      "npm:mathjs@2.6.0/lib/type/matrix/function/matrix",
      "npm:mathjs@2.6.0/lib/type/matrix/function/sparse",
      "npm:mathjs@2.6.0/lib/type/matrix/function/index",
      "npm:mathjs@2.6.0/lib/utils/types",
      "npm:mathjs@2.6.0/lib/utils/function",
      "npm:mathjs@2.6.0/lib/utils/bignumber/atan",
      "npm:mathjs@2.6.0/lib/expression/docs/type/bignumber",
      "npm:mathjs@2.6.0/lib/expression/docs/type/complex",
      "npm:mathjs@2.6.0/lib/expression/docs/type/fraction",
      "npm:mathjs@2.6.0/lib/expression/docs/type/index",
      "npm:mathjs@2.6.0/lib/expression/docs/type/boolean",
      "npm:mathjs@2.6.0/lib/expression/docs/type/matrix",
      "npm:mathjs@2.6.0/lib/expression/docs/type/number",
      "npm:mathjs@2.6.0/lib/expression/docs/type/sparse",
      "npm:mathjs@2.6.0/lib/expression/docs/type/string",
      "npm:mathjs@2.6.0/lib/expression/docs/type/unit",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/false",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/Infinity",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/i",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/e",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/LN2",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/LN10",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/LOG2E",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/NaN",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/LOG10E",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/null",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/pi",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/SQRT1_2",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/tau",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/SQRT2",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/phi",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/true",
      "npm:mathjs@2.6.0/lib/expression/docs/constants/version",
      "npm:mathjs@2.6.0/lib/expression/docs/function/algebra/lsolve",
      "npm:mathjs@2.6.0/lib/expression/docs/function/algebra/lup",
      "npm:mathjs@2.6.0/lib/expression/docs/function/algebra/lusolve",
      "npm:mathjs@2.6.0/lib/expression/docs/function/algebra/slu",
      "npm:mathjs@2.6.0/lib/expression/docs/function/algebra/usolve",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/abs",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/cbrt",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/add",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/ceil",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/divide",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/dotMultiply",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/dotDivide",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/cube",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/exp",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/floor",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/dotPow",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/fix",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/gcd",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/hypot",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/lcm",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/log",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/norm",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/multiply",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/mod",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/log10",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/nthRoot",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/pow",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/sqrt",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/sign",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/round",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/square",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/subtract",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/xgcd",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/unaryMinus",
      "npm:mathjs@2.6.0/lib/expression/docs/function/arithmetic/unaryPlus",
      "npm:mathjs@2.6.0/lib/expression/docs/function/bitwise/bitAnd",
      "npm:mathjs@2.6.0/lib/expression/docs/function/bitwise/bitNot",
      "npm:mathjs@2.6.0/lib/expression/docs/function/bitwise/bitXor",
      "npm:mathjs@2.6.0/lib/expression/docs/function/bitwise/rightArithShift",
      "npm:mathjs@2.6.0/lib/expression/docs/function/bitwise/leftShift",
      "npm:mathjs@2.6.0/lib/expression/docs/function/bitwise/bitOr",
      "npm:mathjs@2.6.0/lib/expression/docs/function/bitwise/rightLogShift",
      "npm:mathjs@2.6.0/lib/expression/docs/function/combinatorics/composition",
      "npm:mathjs@2.6.0/lib/expression/docs/function/combinatorics/catalan",
      "npm:mathjs@2.6.0/lib/expression/docs/function/combinatorics/bellNumbers",
      "npm:mathjs@2.6.0/lib/expression/docs/function/combinatorics/stirlingS2",
      "npm:mathjs@2.6.0/lib/expression/docs/function/complex/re",
      "npm:mathjs@2.6.0/lib/expression/docs/function/complex/conj",
      "npm:mathjs@2.6.0/lib/expression/docs/function/complex/arg",
      "npm:mathjs@2.6.0/lib/expression/docs/function/complex/im",
      "npm:mathjs@2.6.0/lib/expression/docs/function/expression/eval",
      "npm:mathjs@2.6.0/lib/expression/docs/function/geometry/distance",
      "npm:mathjs@2.6.0/lib/expression/docs/function/expression/help",
      "npm:mathjs@2.6.0/lib/expression/docs/function/geometry/intersect",
      "npm:mathjs@2.6.0/lib/expression/docs/function/logical/and",
      "npm:mathjs@2.6.0/lib/expression/docs/function/logical/xor",
      "npm:mathjs@2.6.0/lib/expression/docs/function/logical/or",
      "npm:mathjs@2.6.0/lib/expression/docs/function/logical/not",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/concat",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/cross",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/det",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/diag",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/dot",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/inv",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/flatten",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/eye",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/ones",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/range",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/size",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/squeeze",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/resize",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/subset",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/trace",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/transpose",
      "npm:mathjs@2.6.0/lib/expression/docs/function/probability/combinations",
      "npm:mathjs@2.6.0/lib/expression/docs/function/matrix/zeros",
      "npm:mathjs@2.6.0/lib/expression/docs/function/probability/factorial",
      "npm:mathjs@2.6.0/lib/expression/docs/function/probability/gamma",
      "npm:mathjs@2.6.0/lib/expression/docs/function/probability/multinomial",
      "npm:mathjs@2.6.0/lib/expression/docs/function/probability/permutations",
      "npm:mathjs@2.6.0/lib/expression/docs/function/probability/kldivergence",
      "npm:mathjs@2.6.0/lib/expression/docs/function/probability/pickRandom",
      "npm:mathjs@2.6.0/lib/expression/docs/function/probability/random",
      "npm:mathjs@2.6.0/lib/expression/docs/function/probability/randomInt",
      "npm:mathjs@2.6.0/lib/expression/docs/function/relational/equal",
      "npm:mathjs@2.6.0/lib/expression/docs/function/relational/compare",
      "npm:mathjs@2.6.0/lib/expression/docs/function/relational/deepEqual",
      "npm:mathjs@2.6.0/lib/expression/docs/function/relational/larger",
      "npm:mathjs@2.6.0/lib/expression/docs/function/relational/smallerEq",
      "npm:mathjs@2.6.0/lib/expression/docs/function/relational/smaller",
      "npm:mathjs@2.6.0/lib/expression/docs/function/relational/largerEq",
      "npm:mathjs@2.6.0/lib/expression/docs/function/relational/unequal",
      "npm:mathjs@2.6.0/lib/expression/docs/function/statistics/max",
      "npm:mathjs@2.6.0/lib/expression/docs/function/statistics/median",
      "npm:mathjs@2.6.0/lib/expression/docs/function/statistics/min",
      "npm:mathjs@2.6.0/lib/expression/docs/function/statistics/mean",
      "npm:mathjs@2.6.0/lib/expression/docs/function/statistics/mode",
      "npm:mathjs@2.6.0/lib/expression/docs/function/statistics/quantileSeq",
      "npm:mathjs@2.6.0/lib/expression/docs/function/statistics/prod",
      "npm:mathjs@2.6.0/lib/expression/docs/function/statistics/std",
      "npm:mathjs@2.6.0/lib/expression/docs/function/statistics/sum",
      "npm:mathjs@2.6.0/lib/expression/docs/function/statistics/var",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/acos",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/acot",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/acoth",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/acosh",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/acsc",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/acsch",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/asech",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/asec",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/asin",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/asinh",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/atan2",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/atanh",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/atan",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/cos",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/cosh",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/cot",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/csch",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/csc",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/coth",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/sec",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/sech",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/sin",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/sinh",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/tan",
      "npm:mathjs@2.6.0/lib/expression/docs/function/trigonometry/tanh",
      "npm:mathjs@2.6.0/lib/expression/docs/function/utils/clone",
      "npm:mathjs@2.6.0/lib/expression/docs/function/utils/map",
      "npm:mathjs@2.6.0/lib/expression/docs/function/units/to",
      "npm:mathjs@2.6.0/lib/expression/docs/function/utils/partitionSelect",
      "npm:mathjs@2.6.0/lib/expression/docs/function/utils/format",
      "npm:mathjs@2.6.0/lib/expression/docs/function/utils/filter",
      "npm:mathjs@2.6.0/lib/expression/docs/function/utils/isInteger",
      "npm:mathjs@2.6.0/lib/expression/docs/function/utils/isNegative",
      "npm:mathjs@2.6.0/lib/expression/docs/function/utils/forEach",
      "npm:mathjs@2.6.0/lib/expression/docs/function/utils/isNumeric",
      "npm:mathjs@2.6.0/lib/expression/docs/function/utils/isPositive",
      "npm:mathjs@2.6.0/lib/expression/docs/function/utils/isZero",
      "npm:mathjs@2.6.0/lib/expression/docs/function/utils/import",
      "npm:mathjs@2.6.0/lib/expression/docs/function/utils/sort",
      "npm:mathjs@2.6.0/lib/expression/docs/function/utils/typeof",
      "npm:mathjs@2.6.0/lib/type/complex/Complex",
      "npm:mathjs@2.6.0/lib/type/complex/function/complex",
      "npm:mathjs@2.6.0/lib/type/bignumber/function/bignumber",
      "npm:mathjs@2.6.0/lib/type/fraction/function/fraction",
      "npm:mathjs@2.6.0/lib/type/chain/Chain",
      "npm:mathjs@2.6.0/lib/type/matrix/Matrix",
      "npm:mathjs@2.6.0/lib/type/matrix/FibonacciHeap",
      "npm:mathjs@2.6.0/lib/type/matrix/Spa",
      "npm:mathjs@2.6.0/lib/type/matrix/ImmutableDenseMatrix",
      "npm:mathjs@2.6.0/lib/type/matrix/MatrixIndex",
      "npm:mathjs@2.6.0/lib/type/matrix/Range",
      "npm:mathjs@2.6.0/lib/type/unit/Unit",
      "npm:mathjs@2.6.0/lib/utils/number",
      "npm:mathjs@2.6.0/lib/utils/string",
      "npm:mathjs@2.6.0/lib/type/unit/function/unit",
      "npm:mathjs@2.6.0/lib/type/unit/physicalConstants",
      "npm:mathjs@2.6.0/lib/expression/function/compile",
      "npm:mathjs@2.6.0/lib/expression/function/eval",
      "npm:mathjs@2.6.0/lib/expression/function/parser",
      "npm:mathjs@2.6.0/lib/expression/function/parse",
      "npm:mathjs@2.6.0/lib/expression/function/help",
      "npm:mathjs@2.6.0/lib/expression/node/ArrayNode",
      "npm:mathjs@2.6.0/lib/expression/node/AssignmentNode",
      "npm:mathjs@2.6.0/lib/expression/node/BlockNode",
      "npm:mathjs@2.6.0/lib/expression/node/ConditionalNode",
      "npm:mathjs@2.6.0/lib/expression/node/ConstantNode",
      "npm:mathjs@2.6.0/lib/expression/node/Node",
      "npm:mathjs@2.6.0/lib/expression/node/FunctionAssignmentNode",
      "npm:mathjs@2.6.0/lib/expression/node/IndexNode",
      "npm:mathjs@2.6.0/lib/expression/node/FunctionNode",
      "npm:mathjs@2.6.0/lib/expression/node/OperatorNode",
      "npm:mathjs@2.6.0/lib/expression/node/RangeNode",
      "npm:mathjs@2.6.0/lib/expression/node/ParenthesisNode",
      "npm:mathjs@2.6.0/lib/expression/node/SymbolNode",
      "npm:mathjs@2.6.0/lib/expression/node/UpdateNode",
      "npm:mathjs@2.6.0/lib/expression/transform/filter.transform",
      "npm:mathjs@2.6.0/lib/expression/transform/concat.transform",
      "npm:mathjs@2.6.0/lib/expression/transform/forEach.transform",
      "npm:mathjs@2.6.0/lib/expression/transform/map.transform",
      "npm:mathjs@2.6.0/lib/expression/transform/index.transform",
      "npm:mathjs@2.6.0/lib/expression/transform/mean.transform",
      "npm:mathjs@2.6.0/lib/expression/transform/max.transform",
      "npm:mathjs@2.6.0/lib/expression/transform/min.transform",
      "npm:mathjs@2.6.0/lib/type/fraction/Fraction",
      "npm:mathjs@2.6.0/lib/type/bignumber/BigNumber",
      "npm:mathjs@2.6.0/lib/type/matrix/DenseMatrix",
      "npm:mathjs@2.6.0/lib/type/matrix/SparseMatrix",
      "npm:mathjs@2.6.0/lib/expression/transform/subset.transform",
      "npm:typed-function@0.10.3",
      "npm:mathjs@2.6.0/lib/expression/transform/range.transform",
      "npm:mathjs@2.6.0/lib/function/algebra/decomposition/lup",
      "npm:mathjs@2.6.0/lib/function/algebra/decomposition/slu",
      "npm:mathjs@2.6.0/lib/function/algebra/solver/lusolve",
      "npm:mathjs@2.6.0/lib/function/algebra/solver/lsolve",
      "npm:mathjs@2.6.0/lib/function/bitwise/bitAnd",
      "npm:mathjs@2.6.0/lib/function/algebra/solver/usolve",
      "npm:mathjs@2.6.0/lib/function/arithmetic/addScalar",
      "npm:mathjs@2.6.0/lib/function/utils/map",
      "npm:mathjs@2.6.0/lib/function/utils/forEach",
      "npm:mathjs@2.6.0/lib/function/bitwise/bitNot",
      "npm:mathjs@2.6.0/lib/function/combinatorics/bellNumbers",
      "npm:mathjs@2.6.0/lib/function/complex/arg",
      "npm:mathjs@2.6.0/lib/function/complex/conj",
      "npm:mathjs@2.6.0/lib/function/combinatorics/catalan",
      "npm:mathjs@2.6.0/lib/function/combinatorics/composition",
      "npm:mathjs@2.6.0/lib/function/combinatorics/stirlingS2",
      "npm:mathjs@2.6.0/lib/function/complex/im",
      "npm:mathjs@2.6.0/lib/function/geometry/intersect",
      "npm:mathjs@2.6.0/lib/function/complex/re",
      "npm:mathjs@2.6.0/lib/function/geometry/distance",
      "npm:mathjs@2.6.0/lib/function/matrix/concat",
      "npm:mathjs@2.6.0/lib/function/matrix/cross",
      "npm:mathjs@2.6.0/lib/function/matrix/det",
      "npm:mathjs@2.6.0/lib/function/matrix/diag",
      "npm:mathjs@2.6.0/lib/function/matrix/dot",
      "npm:mathjs@2.6.0/lib/function/matrix/eye",
      "npm:mathjs@2.6.0/lib/function/matrix/inv",
      "npm:mathjs@2.6.0/lib/function/matrix/flatten",
      "npm:mathjs@2.6.0/lib/function/matrix/range",
      "npm:mathjs@2.6.0/lib/function/matrix/resize",
      "npm:mathjs@2.6.0/lib/function/matrix/size",
      "npm:mathjs@2.6.0/lib/function/matrix/squeeze",
      "npm:mathjs@2.6.0/lib/function/matrix/subset",
      "npm:mathjs@2.6.0/lib/function/matrix/zeros",
      "npm:mathjs@2.6.0/lib/function/matrix/ones",
      "npm:mathjs@2.6.0/lib/function/probability/factorial",
      "npm:mathjs@2.6.0/lib/function/probability/gamma",
      "npm:mathjs@2.6.0/lib/function/probability/kldivergence",
      "npm:mathjs@2.6.0/lib/function/probability/permutations",
      "npm:mathjs@2.6.0/lib/function/probability/multinomial",
      "npm:mathjs@2.6.0/lib/function/probability/randomInt",
      "npm:mathjs@2.6.0/lib/function/probability/combinations",
      "npm:mathjs@2.6.0/lib/function/probability/pickRandom",
      "npm:mathjs@2.6.0/lib/function/statistics/mean",
      "npm:mathjs@2.6.0/lib/function/statistics/max",
      "npm:mathjs@2.6.0/lib/function/probability/random",
      "npm:mathjs@2.6.0/lib/function/statistics/min",
      "npm:mathjs@2.6.0/lib/function/statistics/mode",
      "npm:mathjs@2.6.0/lib/function/statistics/median",
      "npm:mathjs@2.6.0/lib/function/statistics/quantileSeq",
      "npm:mathjs@2.6.0/lib/function/statistics/prod",
      "npm:mathjs@2.6.0/lib/function/statistics/sum",
      "npm:mathjs@2.6.0/lib/function/statistics/var",
      "npm:mathjs@2.6.0/lib/function/statistics/std",
      "npm:mathjs@2.6.0/lib/function/logical/not",
      "npm:mathjs@2.6.0/lib/function/relational/deepEqual",
      "npm:mathjs@2.6.0/lib/function/trigonometry/acos",
      "npm:mathjs@2.6.0/lib/function/trigonometry/acosh",
      "npm:mathjs@2.6.0/lib/function/trigonometry/acsc",
      "npm:mathjs@2.6.0/lib/function/trigonometry/acoth",
      "npm:mathjs@2.6.0/lib/function/trigonometry/acot",
      "npm:mathjs@2.6.0/lib/function/trigonometry/acsch",
      "npm:mathjs@2.6.0/lib/function/trigonometry/asec",
      "npm:mathjs@2.6.0/lib/function/trigonometry/asech",
      "npm:mathjs@2.6.0/lib/function/trigonometry/asin",
      "npm:mathjs@2.6.0/lib/function/trigonometry/asinh",
      "npm:mathjs@2.6.0/lib/function/trigonometry/atan",
      "npm:mathjs@2.6.0/lib/function/trigonometry/atanh",
      "npm:mathjs@2.6.0/lib/function/trigonometry/cos",
      "npm:mathjs@2.6.0/lib/function/trigonometry/cosh",
      "npm:mathjs@2.6.0/lib/function/trigonometry/cot",
      "npm:mathjs@2.6.0/lib/function/trigonometry/coth",
      "npm:mathjs@2.6.0/lib/function/trigonometry/sec",
      "npm:mathjs@2.6.0/lib/function/trigonometry/csch",
      "npm:mathjs@2.6.0/lib/function/trigonometry/csc",
      "npm:mathjs@2.6.0/lib/function/trigonometry/sech",
      "npm:mathjs@2.6.0/lib/function/trigonometry/sin",
      "npm:mathjs@2.6.0/lib/function/trigonometry/sinh",
      "npm:mathjs@2.6.0/lib/function/trigonometry/tan",
      "npm:mathjs@2.6.0/lib/function/arithmetic/abs",
      "npm:mathjs@2.6.0/lib/function/trigonometry/tanh",
      "npm:mathjs@2.6.0/lib/function/arithmetic/cbrt",
      "npm:mathjs@2.6.0/lib/function/arithmetic/ceil",
      "npm:mathjs@2.6.0/lib/function/arithmetic/cube",
      "npm:mathjs@2.6.0/lib/function/arithmetic/exp",
      "npm:mathjs@2.6.0/lib/function/arithmetic/fix",
      "npm:mathjs@2.6.0/lib/function/arithmetic/floor",
      "npm:mathjs@2.6.0/lib/function/arithmetic/hypot",
      "npm:mathjs@2.6.0/lib/function/arithmetic/log",
      "npm:mathjs@2.6.0/lib/function/arithmetic/log10",
      "npm:mathjs@2.6.0/lib/function/arithmetic/pow",
      "npm:mathjs@2.6.0/lib/function/arithmetic/norm",
      "npm:mathjs@2.6.0/lib/function/arithmetic/round",
      "npm:mathjs@2.6.0/lib/function/arithmetic/sign",
      "npm:mathjs@2.6.0/lib/function/arithmetic/sqrt",
      "npm:mathjs@2.6.0/lib/function/arithmetic/square",
      "npm:mathjs@2.6.0/lib/function/arithmetic/unaryMinus",
      "npm:mathjs@2.6.0/lib/function/arithmetic/unaryPlus",
      "npm:mathjs@2.6.0/lib/function/arithmetic/xgcd",
      "npm:mathjs@2.6.0/lib/function/utils/clone",
      "npm:mathjs@2.6.0/lib/function/utils/filter",
      "npm:mathjs@2.6.0/lib/function/utils/format",
      "npm:mathjs@2.6.0/lib/function/utils/isInteger",
      "npm:mathjs@2.6.0/lib/function/utils/isNumeric",
      "npm:mathjs@2.6.0/lib/function/utils/isPositive",
      "npm:mathjs@2.6.0/lib/function/utils/isZero",
      "npm:mathjs@2.6.0/lib/function/utils/isNegative",
      "npm:mathjs@2.6.0/lib/function/utils/partitionSelect",
      "npm:mathjs@2.6.0/lib/function/utils/print",
      "npm:mathjs@2.6.0/lib/function/utils/sort",
      "npm:mathjs@2.6.0/lib/function/utils/typeof",
      "npm:mathjs@2.6.0/lib/function/units/to",
      "npm:mathjs@2.6.0/lib/function/bitwise/bitOr",
      "npm:mathjs@2.6.0/lib/function/bitwise/bitXor",
      "npm:mathjs@2.6.0/lib/function/bitwise/leftShift",
      "npm:mathjs@2.6.0/lib/function/bitwise/rightArithShift",
      "npm:mathjs@2.6.0/lib/function/bitwise/rightLogShift",
      "npm:mathjs@2.6.0/lib/function/matrix/trace",
      "npm:mathjs@2.6.0/lib/function/matrix/transpose",
      "npm:mathjs@2.6.0/lib/function/logical/and",
      "npm:mathjs@2.6.0/lib/function/logical/or",
      "npm:mathjs@2.6.0/lib/function/relational/compare",
      "npm:mathjs@2.6.0/lib/function/relational/equal",
      "npm:mathjs@2.6.0/lib/function/relational/largerEq",
      "npm:mathjs@2.6.0/lib/function/relational/larger",
      "npm:mathjs@2.6.0/lib/function/relational/smaller",
      "npm:mathjs@2.6.0/lib/function/relational/smallerEq",
      "npm:mathjs@2.6.0/lib/function/relational/unequal",
      "npm:mathjs@2.6.0/lib/function/logical/xor",
      "npm:mathjs@2.6.0/lib/function/trigonometry/atan2",
      "npm:mathjs@2.6.0/lib/function/arithmetic/add",
      "npm:mathjs@2.6.0/lib/function/arithmetic/divide",
      "npm:mathjs@2.6.0/lib/function/arithmetic/dotDivide",
      "npm:mathjs@2.6.0/lib/function/arithmetic/dotMultiply",
      "npm:mathjs@2.6.0/lib/function/arithmetic/dotPow",
      "npm:mathjs@2.6.0/lib/function/arithmetic/gcd",
      "npm:mathjs@2.6.0/lib/function/arithmetic/lcm",
      "npm:mathjs@2.6.0/lib/function/arithmetic/mod",
      "npm:mathjs@2.6.0/lib/function/arithmetic/multiply",
      "npm:mathjs@2.6.0/lib/function/arithmetic/nthRoot",
      "npm:mathjs@2.6.0/lib/function/arithmetic/subtract",
      "npm:tiny-emitter@1.0.2/index",
      "npm:mathjs@2.6.0/lib/function/arithmetic/multiplyScalar",
      "npm:mathjs@2.6.0/lib/utils/latex",
      "npm:mathjs@2.6.0/lib/utils/NumberFormatter",
      "npm:mathjs@2.6.0/lib/function/relational/equalScalar",
      "npm:mathjs@2.6.0/lib/function/arithmetic/divideScalar",
      "npm:mathjs@2.6.0/lib/expression/keywords",
      "npm:mathjs@2.6.0/lib/utils/bignumber/formatter",
      "npm:mathjs@2.6.0/lib/utils/collection/isCollection",
      "npm:mathjs@2.6.0/lib/expression/operators",
      "npm:fraction.js@3.2.0",
      "npm:mathjs@2.6.0/lib/expression/transform/error.transform",
      "npm:decimal.js@4.0.3",
      "npm:mathjs@2.6.0/lib/utils/index",
      "npm:typed-function@0.10.3/typed-function",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_ipvec",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_sqr",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_lu",
      "npm:mathjs@2.6.0/lib/function/algebra/solver/utils/solveValidation",
      "npm:mathjs@2.6.0/lib/utils/bignumber/bitAnd",
      "npm:mathjs@2.6.0/lib/type/matrix/utils/algorithm06",
      "npm:mathjs@2.6.0/lib/utils/bignumber/bitNot",
      "npm:mathjs@2.6.0/lib/utils/collection/deepForEach",
      "npm:mathjs@2.6.0/lib/utils/bignumber/acoshAsinhAsechAcsch",
      "npm:mathjs@2.6.0/lib/utils/bignumber/atanhAcoth",
      "npm:mathjs@2.6.0/lib/utils/bignumber/coshSinhCschSech",
      "npm:mathjs@2.6.0/lib/utils/bignumber/tanhCoth",
      "npm:mathjs@2.6.0/lib/utils/bignumber/leftShift",
      "npm:mathjs@2.6.0/lib/utils/bignumber/rightArithShift",
      "npm:mathjs@2.6.0/lib/utils/collection/reduce",
      "npm:mathjs@2.6.0/lib/function/probability/distribution",
      "npm:mathjs@2.6.0/lib/utils/bignumber/asinAcsc",
      "npm:mathjs@2.6.0/lib/utils/bignumber/acosAsec",
      "npm:mathjs@2.6.0/lib/utils/bignumber/cosSinSecCsc",
      "npm:mathjs@2.6.0/lib/utils/bignumber/tanCot",
      "npm:mathjs@2.6.0/lib/utils/bignumber/bitOr",
      "npm:mathjs@2.6.0/lib/utils/bignumber/atanAcot",
      "npm:mathjs@2.6.0/lib/utils/bignumber/bitXor",
      "npm:mathjs@2.6.0/lib/utils/bignumber/atan2",
      "npm:mathjs@2.6.0/lib/type/matrix/utils/algorithm11",
      "npm:mathjs@2.6.0/lib/type/matrix/utils/algorithm14",
      "npm:mathjs@2.6.0/lib/type/matrix/utils/algorithm13",
      "npm:mathjs@2.6.0/lib/type/matrix/utils/algorithm12",
      "npm:mathjs@2.6.0/lib/type/matrix/utils/algorithm01",
      "npm:mathjs@2.6.0/lib/type/matrix/utils/algorithm04",
      "npm:mathjs@2.6.0/lib/type/matrix/utils/algorithm10",
      "npm:mathjs@2.6.0/lib/type/matrix/utils/algorithm07",
      "npm:mathjs@2.6.0/lib/type/matrix/utils/algorithm03",
      "npm:mathjs@2.6.0/lib/type/matrix/utils/algorithm08",
      "npm:mathjs@2.6.0/lib/type/matrix/utils/algorithm05",
      "npm:mathjs@2.6.0/lib/type/matrix/utils/algorithm09",
      "npm:mathjs@2.6.0/lib/type/matrix/utils/algorithm02",
      "npm:fraction.js@3.2.0/fraction",
      "npm:mathjs@2.6.0/lib/utils/boolean",
      "npm:decimal.js@4.0.3/decimal",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_permute",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_etree",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_amd",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_post",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_spsolve",
      "npm:mathjs@2.6.0/lib/utils/bignumber/asin",
      "npm:mathjs@2.6.0/lib/utils/bignumber/cosSin",
      "npm:mathjs@2.6.0/lib/utils/bignumber/sinToCos",
      "npm:mathjs@2.6.0/lib/utils/bignumber/bitwise",
      "npm:mathjs@2.6.0/lib/utils/bignumber/asinNewton",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_counts",
      "npm:mathjs@2.6.0/lib/utils/bignumber/reduceToPeriod",
      "npm:mathjs@2.6.0/lib/utils/collection/scatter",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_flip",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_fkeep",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_tdfs",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_reach",
      "github:jspm/nodelibs-crypto@0.1.0",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_leaf",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_marked",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_mark",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_dfs",
      "github:jspm/nodelibs-crypto@0.1.0/index",
      "npm:mathjs@2.6.0/lib/function/algebra/sparse/cs_unflip",
      "npm:crypto-browserify@3.11.0",
      "npm:crypto-browserify@3.11.0/index",
      "npm:randombytes@2.0.2",
      "npm:create-hash@1.1.2",
      "npm:pbkdf2@3.0.4",
      "npm:create-hmac@1.1.4",
      "npm:create-ecdh@4.0.0",
      "npm:browserify-sign@4.0.0/algos",
      "npm:diffie-hellman@5.0.2",
      "npm:browserify-cipher@1.0.0",
      "npm:browserify-sign@4.0.0",
      "npm:public-encrypt@4.0.0",
      "npm:randombytes@2.0.2/browser",
      "github:jspm/nodelibs-buffer@0.1.0",
      "npm:create-hash@1.1.2/browser",
      "npm:create-ecdh@4.0.0/browser",
      "npm:pbkdf2@3.0.4/browser",
      "npm:create-hmac@1.1.4/browser",
      "npm:diffie-hellman@5.0.2/browser",
      "npm:browserify-sign@4.0.0/browser",
      "npm:browserify-cipher@1.0.0/browser",
      "npm:public-encrypt@4.0.0/browser",
      "npm:inherits@2.0.1",
      "npm:create-hash@1.1.2/md5",
      "npm:cipher-base@1.0.2",
      "npm:ripemd160@1.0.1",
      "npm:sha.js@2.4.4",
      "github:jspm/nodelibs-stream@0.1.0",
      "github:jspm/nodelibs-buffer@0.1.0/index",
      "npm:diffie-hellman@5.0.2/lib/generatePrime",
      "npm:bn.js@4.9.0",
      "npm:elliptic@6.2.3",
      "npm:evp_bytestokey@1.0.0",
      "npm:browserify-aes@1.0.6/browser",
      "npm:diffie-hellman@5.0.2/lib/dh",
      "npm:browserify-sign@4.0.0/verify",
      "npm:browserify-sign@4.0.0/sign",
      "npm:browserify-aes@1.0.6/modes",
      "npm:browserify-des@1.0.0/modes",
      "npm:browserify-des@1.0.0",
      "npm:public-encrypt@4.0.0/privateDecrypt",
      "npm:public-encrypt@4.0.0/publicEncrypt",
      "npm:inherits@2.0.1/inherits_browser",
      "npm:create-hash@1.1.2/helpers",
      "npm:ripemd160@1.0.1/lib/ripemd160",
      "github:jspm/nodelibs-stream@0.1.0/index",
      "npm:sha.js@2.4.4/index",
      "npm:cipher-base@1.0.2/index",
      "npm:browserify-sign@4.0.0/curves",
      "npm:bn.js@4.9.0/lib/bn",
      "npm:miller-rabin@4.0.0",
      "npm:buffer@3.6.0",
      "npm:browserify-rsa@4.0.0",
      "npm:parse-asn1@5.0.0",
      "npm:browserify-aes@1.0.6/encrypter",
      "npm:browserify-aes@1.0.6/decrypter",
      "npm:browserify-des@1.0.0/index",
      "npm:public-encrypt@4.0.0/mgf",
      "npm:evp_bytestokey@1.0.0/index",
      "npm:elliptic@6.2.3/lib/elliptic",
      "npm:public-encrypt@4.0.0/xor",
      "npm:diffie-hellman@5.0.2/lib/primes.json!github:systemjs/plugin-json@0.1.0",
      "npm:public-encrypt@4.0.0/withPublic",
      "npm:stream-browserify@1.0.0",
      "npm:sha.js@2.4.4/sha1",
      "npm:sha.js@2.4.4/sha224",
      "npm:sha.js@2.4.4/sha",
      "npm:sha.js@2.4.4/sha256",
      "github:jspm/nodelibs-string_decoder@0.1.0",
      "npm:miller-rabin@4.0.0/lib/mr",
      "npm:buffer@3.6.0/index",
      "npm:sha.js@2.4.4/sha384",
      "npm:sha.js@2.4.4/sha512",
      "npm:browserify-aes@1.0.6/aes",
      "npm:browserify-rsa@4.0.0/index",
      "npm:browserify-aes@1.0.6/streamCipher",
      "npm:browserify-aes@1.0.6/modes/ecb",
      "npm:brorand@1.0.5",
      "npm:des.js@1.0.0",
      "npm:elliptic@6.2.3/lib/elliptic/curve/index",
      "npm:elliptic@6.2.3/lib/elliptic/utils",
      "npm:browserify-aes@1.0.6/modes/cfb",
      "npm:browserify-aes@1.0.6/modes/cbc",
      "npm:browserify-aes@1.0.6/modes/cfb8",
      "npm:browserify-aes@1.0.6/authCipher",
      "npm:browserify-aes@1.0.6/modes/ofb",
      "npm:browserify-aes@1.0.6/modes/cfb1",
      "npm:browserify-aes@1.0.6/modes/ctr",
      "npm:elliptic@6.2.3/lib/elliptic/hmac-drbg",
      "npm:parse-asn1@5.0.0/index",
      "npm:elliptic@6.2.3/package.json!github:systemjs/plugin-json@0.1.0",
      "npm:elliptic@6.2.3/lib/elliptic/ec/index",
      "npm:elliptic@6.2.3/lib/elliptic/eddsa/index",
      "npm:elliptic@6.2.3/lib/elliptic/curves",
      "npm:stream-browserify@1.0.0/index",
      "npm:sha.js@2.4.4/hash",
      "github:jspm/nodelibs-string_decoder@0.1.0/index",
      "npm:base64-js@0.0.8",
      "npm:brorand@1.0.5/index",
      "npm:parse-asn1@5.0.0/aesid.json!github:systemjs/plugin-json@0.1.0",
      "npm:ieee754@1.1.6",
      "npm:isarray@1.0.0",
      "npm:des.js@1.0.0/lib/des",
      "npm:buffer-xor@1.0.3",
      "npm:hash.js@1.0.3",
      "npm:browserify-aes@1.0.6",
      "npm:elliptic@6.2.3/lib/elliptic/eddsa/key",
      "npm:elliptic@6.2.3/lib/elliptic/curve/base",
      "npm:elliptic@6.2.3/lib/elliptic/ec/key",
      "npm:elliptic@6.2.3/lib/elliptic/ec/signature",
      "npm:elliptic@6.2.3/lib/elliptic/eddsa/signature",
      "npm:elliptic@6.2.3/lib/elliptic/curve/short",
      "npm:elliptic@6.2.3/lib/elliptic/curve/mont",
      "npm:elliptic@6.2.3/lib/elliptic/curve/edwards",
      "npm:browserify-aes@1.0.6/ghash",
      "npm:parse-asn1@5.0.0/fixProc",
      "npm:parse-asn1@5.0.0/asn1",
      "npm:elliptic@6.2.3/lib/elliptic/precomputed/secp256k1",
      "npm:readable-stream@1.1.13/writable",
      "github:jspm/nodelibs-events@0.1.1",
      "npm:readable-stream@1.1.13/transform",
      "npm:readable-stream@1.1.13/duplex",
      "npm:readable-stream@1.1.13/readable",
      "npm:readable-stream@1.1.13/passthrough",
      "npm:string_decoder@0.10.31",
      "npm:base64-js@0.0.8/lib/b64",
      "npm:isarray@1.0.0/index",
      "npm:ieee754@1.1.6/index",
      "npm:des.js@1.0.0/lib/des/utils",
      "npm:des.js@1.0.0/lib/des/cipher",
      "npm:des.js@1.0.0/lib/des/des",
      "npm:des.js@1.0.0/lib/des/cbc",
      "npm:des.js@1.0.0/lib/des/ede",
      "npm:buffer-xor@1.0.3/index",
      "npm:hash.js@1.0.3/lib/hash",
      "npm:asn1.js@4.3.0",
      "github:jspm/nodelibs-events@0.1.1/index",
      "npm:readable-stream@1.1.13/lib/_stream_transform",
      "npm:readable-stream@1.1.13/lib/_stream_duplex",
      "npm:readable-stream@1.1.13/lib/_stream_passthrough",
      "npm:readable-stream@1.1.13/lib/_stream_writable",
      "npm:readable-stream@1.1.13/lib/_stream_readable",
      "npm:string_decoder@0.10.31/index",
      "npm:minimalistic-assert@1.0.0",
      "npm:hash.js@1.0.3/lib/hash/common",
      "npm:hash.js@1.0.3/lib/hash/ripemd",
      "npm:hash.js@1.0.3/lib/hash/sha",
      "npm:hash.js@1.0.3/lib/hash/hmac",
      "npm:asn1.js@4.3.0/lib/asn1",
      "npm:hash.js@1.0.3/lib/hash/utils",
      "npm:events@1.0.2",
      "npm:minimalistic-assert@1.0.0/index",
      "npm:core-util-is@1.0.2",
      "npm:isarray@0.0.1",
      "npm:asn1.js@4.3.0/lib/asn1/constants/index",
      "npm:asn1.js@4.3.0/lib/asn1/api",
      "npm:asn1.js@4.3.0/lib/asn1/base/index",
      "npm:events@1.0.2/events",
      "npm:asn1.js@4.3.0/lib/asn1/decoders/index",
      "npm:asn1.js@4.3.0/lib/asn1/encoders/index",
      "npm:core-util-is@1.0.2/lib/util",
      "github:jspm/nodelibs-vm@0.1.0",
      "npm:asn1.js@4.3.0/lib/asn1/constants/der",
      "npm:isarray@0.0.1/index",
      "npm:asn1.js@4.3.0/lib/asn1/base/buffer",
      "npm:asn1.js@4.3.0/lib/asn1/base/node",
      "npm:asn1.js@4.3.0/lib/asn1/decoders/pem",
      "npm:asn1.js@4.3.0/lib/asn1/base/reporter",
      "npm:asn1.js@4.3.0/lib/asn1/encoders/der",
      "npm:asn1.js@4.3.0/lib/asn1/decoders/der",
      "npm:asn1.js@4.3.0/lib/asn1/encoders/pem",
      "github:jspm/nodelibs-vm@0.1.0/index",
      "npm:vm-browserify@0.0.4",
      "npm:vm-browserify@0.0.4/index",
      "npm:indexof@0.0.1",
      "npm:indexof@0.0.1/index"
    ]
  },

  map: {
    "babel": "npm:babel-core@5.8.35",
    "babel-runtime": "npm:babel-runtime@5.8.35",
    "core-js": "npm:core-js@1.2.6",
    "d3": "github:mbostock/d3@3.5.14",
    "jquery": "npm:jquery@2.2.0",
    "kristoferjoseph/flexboxgrid": "github:kristoferjoseph/flexboxgrid@6.3.0",
    "mathjs": "npm:mathjs@2.6.0",
    "modernizr": "github:Modernizr/Modernizr@3.3.1",
    "text": "github:systemjs/plugin-text@0.0.4",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:asn1.js@4.3.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@4.9.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.35": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:browserify-aes@1.0.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.2",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@4.0.0": {
      "bn.js": "npm:bn.js@4.9.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.2"
    },
    "npm:browserify-sign@4.0.0": {
      "bn.js": "npm:bn.js@4.9.0",
      "browserify-rsa": "npm:browserify-rsa@4.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:cipher-base@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@1.2.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.9.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.4"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.11.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.0",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@5.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.2"
    },
    "npm:decimal.js@4.0.3": {
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diffie-hellman@5.0.2": {
      "bn.js": "npm:bn.js@4.9.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.0",
      "randombytes": "npm:randombytes@2.0.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:elliptic@6.2.3": {
      "bn.js": "npm:bn.js@4.9.0",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:mathjs@2.6.0": {
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "decimal.js": "npm:decimal.js@4.0.3",
      "fraction.js": "npm:fraction.js@3.2.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "readline": "github:jspm/nodelibs-readline@0.1.0",
      "repl": "github:jspm/nodelibs-repl@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0",
      "tiny-emitter": "npm:tiny-emitter@1.0.2",
      "typed-function": "npm:typed-function@0.10.3"
    },
    "npm:miller-rabin@4.0.0": {
      "bn.js": "npm:bn.js@4.9.0",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:parse-asn1@5.0.0": {
      "asn1.js": "npm:asn1.js@4.3.0",
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.9.0",
      "browserify-rsa": "npm:browserify-rsa@4.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "randombytes": "npm:randombytes@2.0.2"
    },
    "npm:randombytes@2.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:sha.js@2.4.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.13"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    }
  }
});
